#!/bin/bash
set -euo pipefail
# =============================================================================
# Supabase Docker Install Script
# =============================================================================
# Bootstraps a self-hosted Supabase project with the official installer
# (supabase.link/setup.sh -> supabase/supabase's docker/ tree), then wires it
# up behind a host Nginx reverse proxy, matching every other app in this repo:
#
#   /var/www/docker/supabase/<domain>/
#     |-- (everything setup.sh creates: docker-compose.yml, run.sh, .env, ...)
#     `-- docker-compose.override.yml   written here - rebinds api-gw to
#                                        127.0.0.1:<port> only
#
# Deliberately does NOT enable Supabase's own nginx/caddy/kong docker-compose
# overrides. The default api-gw (Envoy) already reverse-proxies everything
# behind it - Studio, Auth, REST, Realtime, Storage, Functions, MCP, SSO -
# on one port, including basic-auth on the dashboard route. So all a host
# Nginx vhost needs is that one port. docker-compose.override.yml is
# Supabase's own gitignored, update.sh-ignored customization slot (see
# update.sh's header and the vendored .gitignore) - not a filename invented
# here - so `update.sh` upgrades keep working untouched.
#
# Secrets (JWT_SECRET, ANON_KEY, SERVICE_ROLE_KEY, DASHBOARD_PASSWORD, ...)
# are generated by setup.sh itself via utils/generate-keys.sh and
# utils/add-new-auth-keys.sh - this script never invents its own.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NGINX_CONF_SRC="$SCRIPT_DIR/../supabase-nginx.conf"

SETUP_SH_URL="https://supabase.link/setup.sh"
SUPABASE_BASE="/var/www/docker/supabase"
DEFAULT_PORT="8000"

# ── Helpers ───────────────────────────────────────────────────────────────────

_die() { echo "ERROR: $*" >&2; exit 1; }

_valid_domain() {
  [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]
}

_valid_port() {
  [[ "$1" =~ ^[0-9]+$ ]] && [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

_port_in_use() {
  command -v ss >/dev/null 2>&1 || return 1
  ss -ltnH 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${1}$"
}

_read_env() {  # _read_env <file> <key>
  grep "^$2=" "$1" 2>/dev/null | head -n1 | cut -d= -f2-
}

# ── Dependency check ──────────────────────────────────────────────────────────
for cmd in docker git curl openssl jq sed; do
  command -v "$cmd" >/dev/null 2>&1 || _die "'$cmd' is required but not installed."
done
docker compose version >/dev/null 2>&1 || _die "the Docker Compose plugin ('docker compose') is required."

echo ""
echo "=====> Supabase Install"
echo "========================================"
echo "Installer source: $SETUP_SH_URL"
echo ""

# ── 1. Domain ─────────────────────────────────────────────────────────────────
read -rp "Enter domain name (e.g. supabase.example.com): " domain
[[ -n "$domain" ]] || _die "Domain cannot be empty."
_valid_domain "$domain" || _die "'$domain' is not a valid domain name."
domain="${domain,,}"   # hostnames are case-insensitive; compose project dir stays lowercase

# ── 2. Host port ──────────────────────────────────────────────────────────────
echo ""
echo "Supabase (Studio + all APIs, through api-gw) is published on"
echo "127.0.0.1:<port> and proxied by Nginx."
read -rp "Host port [$DEFAULT_PORT]: " answer
port="${answer:-$DEFAULT_PORT}"
_valid_port "$port" || _die "Port must be a number between 1 and 65535."
if _port_in_use "$port"; then
  echo ""
  echo "WARNING: something is already listening on port $port:"
  ss -ltnp 2>/dev/null | grep -E "[:.]${port}[[:space:]]" || true
  read -rp "Continue anyway? [y/N] " ans_port
  [[ "$ans_port" =~ ^[Yy]$ ]] || _die "Aborted - pick a free port."
fi

# ── Derived paths ─────────────────────────────────────────────────────────────
INSTALL_DIR="$SUPABASE_BASE/$domain"
ENV_FILE="$INSTALL_DIR/.env"
OVERRIDE_FILE="$INSTALL_DIR/docker-compose.override.yml"

if [ -e "$INSTALL_DIR" ] && [ -n "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
  _die "$INSTALL_DIR already exists and is not empty - remove it first, or choose another domain."
fi

echo ""
echo "==================== SUMMARY ===================="
echo "Domain          : $domain"
echo "URL             : https://$domain"
echo "Host port       : 127.0.0.1:$port  ->  api-gw :8000 (Studio + all APIs)"
echo "Install dir     : $INSTALL_DIR"
echo "Secrets         : generated by setup.sh (printed once below - save them)"
echo "================================================="
echo ""
read -rp "Proceed? [Y/n] " ans_proceed
[[ "$ans_proceed" =~ ^[Nn]$ ]] && { echo "Aborted."; exit 0; }

# ── Bootstrap with the official installer ─────────────────────────────────────
echo ""
echo "==> Creating $SUPABASE_BASE"
sudo mkdir -p "$SUPABASE_BASE"
sudo chown "$(id -u):$(id -g)" "$SUPABASE_BASE"
cd "$SUPABASE_BASE"

SETUP_TMP="$(mktemp)"
trap 'rm -f "$SETUP_TMP"' EXIT
echo "==> Fetching $SETUP_SH_URL"
curl -fsSL "$SETUP_SH_URL" -o "$SETUP_TMP" || _die "could not download setup.sh"

echo "==> Running setup.sh (non-interactive; URLs/port are patched afterward)"
sh "$SETUP_TMP" -y --skip-deps --project-dir "$domain"
rm -f "$SETUP_TMP"
trap - EXIT

[ -f "$ENV_FILE" ] || _die "setup.sh did not produce $ENV_FILE - check its output above."
cd "$INSTALL_DIR"

# ── Patch .env: real URLs and port ────────────────────────────────────────────
echo "==> Configuring .env for https://$domain on port $port"
sed -i.old \
  -e "s|^SUPABASE_PUBLIC_URL=.*$|SUPABASE_PUBLIC_URL=https://${domain}|" \
  -e "s|^API_EXTERNAL_URL=.*$|API_EXTERNAL_URL=https://${domain}/auth/v1|" \
  -e "s|^SITE_URL=.*$|SITE_URL=https://${domain}|" \
  -e "s|^PROXY_DOMAIN=.*$|PROXY_DOMAIN=${domain}|" \
  -e "s|^API_GW_HTTP_PORT=.*$|API_GW_HTTP_PORT=${port}|" \
  "$ENV_FILE"
rm -f "$ENV_FILE.old"
grep -q "^API_GW_HTTP_PORT=" "$ENV_FILE" || echo "API_GW_HTTP_PORT=${port}" >> "$ENV_FILE"

# ── Loopback-only override, and no nginx/caddy/kong docker overrides ─────────
echo "==> Writing docker-compose.override.yml (binds api-gw to 127.0.0.1 only)"
cat > "$OVERRIDE_FILE" <<EOF
# Rebinds api-gw's published port to 127.0.0.1 only, so the only way in is
# through the host Nginx vhost (../../supabase-nginx.conf in this repo).
# Written by supabase-docker-install.sh. This filename is Supabase's own
# gitignored, update.sh-ignored customization slot - not enabled via
# 'run.sh config add', native docker compose merges it automatically once
# it's listed in COMPOSE_FILE (see below).

services:
  api-gw:
    ports: !override
      - "127.0.0.1:\${API_GW_HTTP_PORT:-8000}:8000/tcp"
EOF

sh run.sh config add override >/dev/null
echo "==> Active compose files: $(sh run.sh config)"

# ── Review ────────────────────────────────────────────────────────────────────
read -rp "Would you like to review/edit .env? [y/N] " ans_env
[[ "$ans_env" =~ ^[Yy]$ ]] && "${EDITOR:-vim}" "$ENV_FILE"

read -rp "Would you like to review/edit docker-compose.override.yml? [y/N] " ans_compose
[[ "$ans_compose" =~ ^[Yy]$ ]] && "${EDITOR:-vim}" "$OVERRIDE_FILE"

# ── Start ────────────────────────────────────────────────────────────────────
echo ""
echo "==> Starting Supabase..."
sh run.sh start

# ── Wait for Supabase to answer ───────────────────────────────────────────────
echo -n "==> Waiting for Supabase to respond on 127.0.0.1:$port"
SUPABASE_UP=false
for _ in $(seq 1 60); do
  CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 \
    "http://127.0.0.1:${port}/auth/v1/health" 2>/dev/null || echo "000")
  if [ "$CODE" = "200" ]; then
    SUPABASE_UP=true
    break
  fi
  echo -n "."
  sleep 3
done
echo ""

if [[ "$SUPABASE_UP" == "true" ]]; then
  echo "==> Supabase is up."
else
  echo "WARNING: Supabase did not answer within ~3 minutes."
  echo "         Check the logs: (cd $INSTALL_DIR && sh run.sh logs)"
  read -rp "Continue with the Nginx setup anyway? [y/N] " ans_continue
  [[ "$ans_continue" =~ ^[Yy]$ ]] || exit 1
fi

# ── Let's Encrypt ─────────────────────────────────────────────────────────────
echo ""
read -rp "Would you like to obtain a Let's Encrypt certificate now? [y/N] " ans_cert
if [[ "$ans_cert" =~ ^[Yy]$ ]]; then
  sudo certbot certonly --nginx -d "$domain"
fi

# ── Nginx reverse proxy ───────────────────────────────────────────────────────
read -rp "Would you like to set up the Nginx reverse proxy? [y/N] " ans_nginx
if [[ "$ans_nginx" =~ ^[Yy]$ ]]; then
  NGINX_AVAIL="/etc/nginx/sites-available/$domain"

  [[ -f "$NGINX_CONF_SRC" ]] || _die "nginx config template not found at $NGINX_CONF_SRC"

  sudo cp "$NGINX_CONF_SRC" "$NGINX_AVAIL"
  sudo sed -i \
    -e "s|supabase\.example\.com|$domain|g" \
    -e "s|127\.0\.0\.1:8000|127.0.0.1:$port|g" \
    "$NGINX_AVAIL"
  echo "==> Nginx config written to $NGINX_AVAIL"

  read -rp "Would you like to enable the site (link to sites-enabled)? [y/N] " ans_link
  if [[ "$ans_link" =~ ^[Yy]$ ]]; then
    sudo ln -sf "$NGINX_AVAIL" "/etc/nginx/sites-enabled/$domain"
    echo "==> Symlink created."
  fi

  echo "==> Testing Nginx configuration..."
  sudo nginx -t
  echo "==> Reloading Nginx..."
  sudo systemctl reload nginx
  echo "==> Nginx reloaded."
fi

# ── Done ────────────────────────────────────────────────────────────────────
dashboard_user="$(_read_env "$ENV_FILE" DASHBOARD_USERNAME)"
dashboard_pass="$(_read_env "$ENV_FILE" DASHBOARD_PASSWORD)"

echo ""
echo "==> Supabase installation complete."
echo "    URL           : https://$domain"
echo "    Dashboard user: ${dashboard_user:-(see .env)}"
echo "    Dashboard pass: ${dashboard_pass:-(see .env)}"
echo "    Install dir   : $INSTALL_DIR"
echo "    Secrets       : $ENV_FILE (mode 600 by setup.sh - back this up)"
echo ""
echo "    Useful commands (run from $INSTALL_DIR):"
echo "    Start/stop/restart : sh run.sh start | stop | restart"
echo "    Status/logs         : sh run.sh status | logs [service]"
echo "    Show all secrets    : sh run.sh secrets"
echo "    Show active overrides: sh run.sh config"
echo "    Update (3-way merge): sh update.sh"
echo ""
