#!/bin/bash
set -euo pipefail
# =============================================================================
# Bitwarden Docker Install Script
# =============================================================================
# Installs the official, unmodified Bitwarden self-hosted stack (web, api,
# identity, sso, admin, icons, notifications, events, attachments, nginx,
# mssql) behind a host Nginx reverse proxy.
#
# It follows Bitwarden's own installer (bitwarden.sh -> run.sh -> the official
# ghcr.io/bitwarden/setup image) step for step, but answers the prompts up
# front and switches the bundled nginx container to "behind a proxy" mode:
#
#   Internet -> host nginx :443 (TLS, certbot) -> 127.0.0.1:<port>
#            -> bitwarden-nginx (plain HTTP :8080) -> web/api/identity/...
#
#   <install-dir>/
#     |-- manage.sh            start/stop/update/backup (copy of manage script)
#     |-- bitwarden.conf       domain, port, pinned versions
#     `-- bwdata/              generated by the official Setup image
#         |-- config.yml       the supported place to customize the install
#         |-- docker/docker-compose.yml   generated - do not edit
#         |-- nginx/default.conf          generated - do not edit
#         |-- env/global.override.env     SMTP, admins, secrets
#         |-- mssql/ core/ identity/ logs/ ...   persistent data
#
# Only ONE Bitwarden can run per host: the official compose file uses fixed
# container names (bitwarden-*).
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NGINX_CONF_SRC="$SCRIPT_DIR/../bitwarden-nginx.conf"
MANAGE_SRC="$SCRIPT_DIR/bitwarden-docker-manage.sh"

DEFAULT_BASE="/var/www/docker/bitwarden"
DEFAULT_PORT="8086"
REGISTRY="ghcr.io/bitwarden"
VERSIONS_URL="https://go.btwrdn.com/bw-sh-versions"

# ── Helpers ───────────────────────────────────────────────────────────────────

_die() { echo "ERROR: $*" >&2; exit 1; }

_valid_domain() {
  [[ "$1" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+$ ]]
}

_valid_port() {
  [[ "$1" =~ ^[0-9]+$ ]] && [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

_port_in_use() {
  command -v ss >/dev/null 2>&1 || return 1
  ss -ltnH 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${1}$"
}

_valid_email() { [[ "$1" == *@*.* ]]; }

_mask() { [[ -n "${1:-}" ]] && echo "(set, ${#1} chars)" || echo "(empty)"; }

# _ask_required <var-name> <prompt> [silent]
_ask_required() {
  local -n _ref="$1"
  local prompt="$2" silent="${3:-}" value
  while :; do
    if [[ -n "$silent" ]]; then read -rsp "$prompt" value; echo; else read -rp "$prompt" value; fi
    if [[ -n "$value" ]]; then _ref="$value"; return 0; fi
    echo "    This value is required."
  done
}

# _replace_line <file> <prefix> <new-line>
# Replaces the first line starting with <prefix> (no regex, no sed escaping);
# fails if there is no such line, so a Setup format change is noticed.
_replace_line() {
  local file="$1" prefix="$2" line="$3" tmp
  tmp="$(mktemp)"
  P="$prefix" L="$line" awk '
    !done && index($0, ENVIRON["P"]) == 1 { print ENVIRON["L"]; done = 1; next }
    { print }' "$file" > "$tmp"
  cat "$tmp" > "$file"
  rm -f "$tmp"
  grep -qxF -- "$line" "$file" || _die "'$prefix' not found in $file - Setup output format changed?"
}

# _env_value <value> - value as it must be written to an env_file. Compose
# interpolates $ inside env_file values, so a value with $ is single-quoted
# (literal); a value containing both $ and ' cannot be expressed safely.
_env_value() {
  local v="$1"
  if [[ "$v" == *\$* ]]; then
    [[ "$v" != *\'* ]] || _die "A value containing both \$ and ' cannot be written safely - choose another."
    printf "'%s'" "$v"
  else
    printf '%s' "$v"
  fi
}

# _set_env <file> <key> <value> - replace the key's line, or append it when the
# generated file doesn't have it (optional variables such as startTls).
_set_env() {
  if grep -q "^$2=" "$1"; then
    _replace_line "$1" "$2=" "$2=$(_env_value "$3")"
  else
    printf '%s=%s\n' "$2" "$(_env_value "$3")" >> "$1"
  fi
}

# _smtp_probe <host> <port> - plain TCP reachability from this host (the
# containers use the same outbound path), like Bitwarden's telnet test.
_smtp_probe() { timeout 8 bash -c "exec 3<>/dev/tcp/$1/$2" 2>/dev/null; }

# ── Dependency check ──────────────────────────────────────────────────────────
[ "$(id -u)" -ne 0 ] || _die "Do not install Bitwarden as root (Bitwarden's docs: it breaks the installation). Run as a normal user in the docker group."
for cmd in docker curl awk sed grep sudo; do
  command -v "$cmd" >/dev/null 2>&1 || _die "'$cmd' is required but not installed."
done
docker compose version >/dev/null 2>&1 || _die "the Docker Compose plugin ('docker compose') is required."
docker info >/dev/null 2>&1 || _die "cannot talk to Docker - is your user in the 'docker' group (log out/in after 'usermod -aG docker \$USER')?"
[ -f "$NGINX_CONF_SRC" ] || _die "bitwarden-nginx.conf not found at $NGINX_CONF_SRC"
[ -f "$MANAGE_SRC" ]     || _die "bitwarden-docker-manage.sh not found at $MANAGE_SRC"
if docker ps -a --format '{{.Names}}' | grep -q '^bitwarden-'; then
  _die "Bitwarden containers already exist on this host (fixed names bitwarden-*). Only one instance per host is supported."
fi

echo ""
echo "=====> Bitwarden Install"
echo "========================================"
echo "Requirements: 2GB RAM (4GB recommended), 12GB disk, Docker Engine 26+."
echo ""

# ── 1. Domain ─────────────────────────────────────────────────────────────────
read -rp "Enter domain name (e.g. vault.example.com): " domain
[[ -n "$domain" ]] || _die "Domain cannot be empty."
_valid_domain "$domain" || _die "'$domain' is not a valid domain name."
domain="${domain,,}"

# ── 2. Install directory ──────────────────────────────────────────────────────
echo ""
read -rp "Install directory [$DEFAULT_BASE/$domain]: " answer
INSTALL_DIR="${answer:-$DEFAULT_BASE/$domain}"
INSTALL_DIR="${INSTALL_DIR/#\~/$HOME}"
INSTALL_DIR="${INSTALL_DIR%/}"
[[ "$INSTALL_DIR" = /* ]] || _die "Install directory must be an absolute path."
if [ -e "$INSTALL_DIR" ] && [ -n "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
  _die "$INSTALL_DIR already exists and is not empty - remove it first, or choose another path."
fi

# ── 3. Host port ──────────────────────────────────────────────────────────────
echo ""
echo "Bitwarden's bundled nginx is published on 127.0.0.1:<port> (HTTP) and"
echo "proxied by the host Nginx."
read -rp "Host port [$DEFAULT_PORT]: " answer
port="${answer:-$DEFAULT_PORT}"
_valid_port "$port" || _die "Port must be a number between 1 and 65535."
if _port_in_use "$port"; then
  echo ""
  echo "WARNING: something is already listening on port $port:"
  ss -ltnp 2>/dev/null | grep -E "[:.]${port}[[:space:]]" || true
  read -rp "Continue anyway? [y/N] " ans_port
  [[ "$ans_port" =~ ^[Yy]$ ]] || _die "Aborted - pick a free port."
fi

# ── 4. Installation id / key ──────────────────────────────────────────────────
echo ""
echo "Bitwarden requires an installation id and key (free, tied to an email):"
echo "  https://bitwarden.com/host"
_ask_required install_id  "  Installation id: "
[[ "$install_id" =~ ^[0-9A-Fa-f]{8}(-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$ ]] || _die "Installation id must be a GUID."
_ask_required install_key "  Installation key (input hidden): " silent
read -rp "  Region the id/key were issued in (US/EU) [US]: " region
region="${region:-US}"; region="${region^^}"
[[ "$region" == "US" || "$region" == "EU" ]] || _die "Region must be US or EU."

# ── 5. SMTP (required) ───────────────────────────────────────────────────────
# Bitwarden self-host needs SMTP for account verification, org invites and
# System Administrator Portal access (temp/smtp.txt). It is read by the api,
# identity, admin and notifications containers from global.override.env.
echo ""
echo "SMTP is required by Bitwarden self-hosted (verification, invites, admin portal)."
echo "Recommended: port 587 with STARTTLS. Avoid port 25 (server-to-server relay only)."
echo ""
_ask_required smtp_host "  SMTP host (e.g. mail.example.com): "
read -rp "  SMTP port [587]: " smtp_port
smtp_port="${smtp_port:-587}"
_valid_port "$smtp_port" || _die "SMTP port must be a number between 1 and 65535."
if [[ "$smtp_port" == "25" ]]; then
  echo "  WARNING: port 25 is commonly blocked and unsuitable for application email."
fi
tls_default="1"; [[ "$smtp_port" == "465" ]] && tls_default="2"
[[ "$smtp_port" == "25" ]] && tls_default="3"
echo "  Encryption:"
echo "    1) STARTTLS   (port 587 - recommended)"
echo "    2) Implicit SSL/TLS   (port 465)"
echo "    3) None       (not recommended)"
read -rp "  Select [1-3] [$tls_default]: " tls_choice
case "${tls_choice:-$tls_default}" in
  1) smtp_ssl="false"; smtp_starttls="true"  ;;
  2) smtp_ssl="true";  smtp_starttls="false" ;;
  3) smtp_ssl="false"; smtp_starttls="false" ;;
  *) _die "Encryption must be 1, 2 or 3." ;;
esac
read -rp "  Username (blank if the server needs no login): " smtp_username
smtp_password=""
if [[ -n "$smtp_username" ]]; then
  while :; do
    _ask_required smtp_password "  Password (input hidden): " silent
    # Bitwarden's environment-variables docs: $ is not supported in SMTP passwords.
    if [[ "$smtp_password" == *\$* ]]; then
      echo "    Bitwarden does not support '\$' in SMTP passwords - use another password."
      continue
    fi
    break
  done
fi
smtp_trust="false"
read -rp "  Trust the server certificate without validating it (self-signed; NOT for production)? [y/N] " ans_trust
[[ "$ans_trust" =~ ^[Yy]$ ]] && smtp_trust="true"
# Most servers only let a login send as its own address (else 5.7.1 "Sender
# address rejected: not owned by user"), so default to the login when it is one.
from_default="no-reply@$domain"
[[ "$smtp_username" == *@*.* ]] && from_default="$smtp_username"
read -rp "  Sender address - must be allowed for this login [$from_default]: " smtp_from
smtp_from="${smtp_from:-$from_default}"
_valid_email "$smtp_from" || _die "'$smtp_from' does not look like a valid email address."
echo -n "  Checking that $smtp_host:$smtp_port is reachable... "
if _smtp_probe "$smtp_host" "$smtp_port"; then
  echo "ok"
else
  echo "FAILED"
  echo "  Cannot open a TCP connection from this host (wrong host/port, or outbound blocked)."
  read -rp "  Continue anyway? [y/N] " ans_smtp_continue
  [[ "$ans_smtp_continue" =~ ^[Yy]$ ]] || _die "Aborted - fix SMTP connectivity first."
fi
enable_email_verification="false"
read -rp "  Require email verification for new accounts? [Y/n] " ans_verify
[[ "$ans_verify" =~ ^[Nn]$ ]] || enable_email_verification="true"

echo ""
read -rp "System Administrator Portal admin email(s), comma separated (optional): " admin_emails

# ── 6. Versions ───────────────────────────────────────────────────────────────
echo ""
echo "==> Reading current Bitwarden release versions..."
core_version=""; web_version=""; kc_version=""
if json="$(curl -fsS --max-time 20 "$VERSIONS_URL" 2>/dev/null | tr -d '\n')"; then
  _field() { printf '%s' "$json" | sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p"; }
  core_version="$(_field coreVersion)"; web_version="$(_field webVersion)"; kc_version="$(_field keyConnectorVersion)"
fi
if [[ -z "$core_version" || -z "$web_version" || -z "$kc_version" ]]; then
  echo "WARNING: could not read $VERSIONS_URL."
  read -rp "  Core version (e.g. 2025.1.0) [latest]: " core_version;  core_version="${core_version:-latest}"
  read -rp "  Web version [latest]: " web_version;                   web_version="${web_version:-latest}"
  read -rp "  Key Connector version [latest]: " kc_version;          kc_version="${kc_version:-latest}"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "==================== SUMMARY ===================="
echo "Domain          : $domain"
echo "URL             : https://$domain"
echo "Install dir     : $INSTALL_DIR"
echo "Host port       : 127.0.0.1:$port  ->  bitwarden-nginx :8080 (HTTP)"
echo "Versions        : core $core_version, web $web_version, key-connector $kc_version"
echo "Installation id : $install_id ($region)"
echo "Installation key: $(_mask "$install_key")"
echo "SMTP            : $smtp_host:$smtp_port (ssl=$smtp_ssl, startTls=$smtp_starttls, trustServer=$smtp_trust)"
echo "SMTP login      : ${smtp_username:-(none)} / $(_mask "$smtp_password")   sender: $smtp_from"
echo "Email verify    : $enable_email_verification"
echo "Admin portal    : ${admin_emails:-(none)}"
echo "Database        : official MSSQL container, data in $INSTALL_DIR/bwdata/mssql"
echo "Secrets         : DB password, identity cert, keys - generated by Bitwarden Setup"
echo "================================================="
echo ""
read -rp "Proceed? [Y/n] " ans_proceed
[[ "$ans_proceed" =~ ^[Nn]$ ]] && { echo "Aborted."; exit 0; }

# ── Create the install directory ─────────────────────────────────────────────
echo ""
echo "==> Creating $INSTALL_DIR"
sudo mkdir -p "$INSTALL_DIR"
sudo chown -R "$(id -u):$(id -g)" "$INSTALL_DIR"
chmod 700 "$INSTALL_DIR"
cd "$INSTALL_DIR"
BWDATA="$INSTALL_DIR/bwdata"

cat > bitwarden.conf <<CONF_EOF
# Written by bitwarden-docker-install.sh / manage.sh update - do not edit by hand.
DOMAIN=$domain
PORT=$port
CORE_VERSION=$core_version
WEB_VERSION=$web_version
KEYCONNECTOR_VERSION=$kc_version
CONF_EOF
chmod 600 bitwarden.conf

cp "$MANAGE_SRC" manage.sh
chmod 700 manage.sh
echo "==> manage.sh installed"

# Containers run as this user/group (Bitwarden's run.sh uses the docker group's
# GID); bwdata files end up owned by it. Same as `bitwarden.sh install`.
mkdir -p "$BWDATA/env"
LOCAL_UID="$(id -u)"
LOCAL_GID="$(getent group docker | cut -d: -f3 || true)"
LOCAL_GID="${LOCAL_GID:-$(id -g)}"
printf 'LOCAL_UID=%s\nLOCAL_GID=%s\n' "$LOCAL_UID" "$LOCAL_GID" > "$BWDATA/env/uid.env"

# ── Official Setup: generate all assets ──────────────────────────────────────
echo "==> Pulling the official Setup image..."
docker pull "$REGISTRY/setup:$core_version" >/dev/null
echo "==> Running Bitwarden Setup (installation id is validated online)..."
docker run --rm --name bitwarden-setup --network host \
  -v "$BWDATA:/bitwarden" --env-file "$BWDATA/env/uid.env" \
  "$REGISTRY/setup:$core_version" /app/Setup \
  -install 1 -domain "$domain" -letsencrypt n -skip-ssl 1 \
  -install-id "$install_id" -install-key "$install_key" -cloud-region "$region" \
  -os lin -corev "$core_version" -webv "$web_version" -keyconnectorv "$kc_version"
[ -f "$BWDATA/config.yml" ] || _die "Setup did not produce $BWDATA/config.yml - see its output above."

# ── config.yml: behind-a-proxy mode ──────────────────────────────────────────
# ssl: false + https URL + loopback-only HTTP port is Bitwarden's documented
# reverse-proxy layout. real_ips lets bitwarden-nginx see real client IPs from
# the X-Forwarded-For sent by the host Nginx (connections arrive from Docker's
# private bridge ranges; the port is bound to loopback so only the host can
# reach it).
echo "==> Configuring bwdata/config.yml for the reverse proxy"
CONFIG_YML="$BWDATA/config.yml"
_replace_line "$CONFIG_YML" "url:"        "url: https://$domain"
_replace_line "$CONFIG_YML" "http_port:"  "http_port: '127.0.0.1:$port'"
_replace_line "$CONFIG_YML" "https_port:" "https_port: ''"
_replace_line "$CONFIG_YML" "ssl:"        "ssl: false"
_replace_line "$CONFIG_YML" "real_ips:"   "real_ips: ['172.16.0.0/12', '192.168.0.0/16', '10.0.0.0/8']"

# ── global.override.env: SMTP + admins ───────────────────────────────────────
ENV_FILE="$BWDATA/env/global.override.env"
_set_env "$ENV_FILE" globalSettings__mail__smtp__host       "$smtp_host"
_set_env "$ENV_FILE" globalSettings__mail__smtp__port       "$smtp_port"
_set_env "$ENV_FILE" globalSettings__mail__smtp__ssl        "$smtp_ssl"
_set_env "$ENV_FILE" globalSettings__mail__smtp__startTls   "$smtp_starttls"
_set_env "$ENV_FILE" globalSettings__mail__smtp__username   "$smtp_username"
_set_env "$ENV_FILE" globalSettings__mail__smtp__password   "$smtp_password"
_set_env "$ENV_FILE" globalSettings__mail__replyToEmail     "$smtp_from"
[[ "$smtp_trust" != "true" ]] || _set_env "$ENV_FILE" globalSettings__mail__smtp__trustServer true
_set_env "$ENV_FILE" globalSettings__enableEmailVerification "$enable_email_verification"
[[ -z "$admin_emails" ]] || _set_env "$ENV_FILE" adminSettings__admins "$admin_emails"
chmod 600 "$ENV_FILE"

# ── Review ──────────────────────────────────────────────────────────────────-
read -rp "Would you like to review/edit config.yml? [y/N] " ans_cfg
[[ "$ans_cfg" =~ ^[Yy]$ ]] && "${EDITOR:-vim}" "$CONFIG_YML"
read -rp "Would you like to review/edit global.override.env? [y/N] " ans_env
[[ "$ans_env" =~ ^[Yy]$ ]] && "${EDITOR:-vim}" "$ENV_FILE"

# ── Regenerate assets from config.yml, migrate the database, start ───────────
echo ""
echo "==> Rebuilding assets from config.yml..."
./manage.sh rebuild
grep -q "127.0.0.1:$port:8080" "$BWDATA/docker/docker-compose.yml" \
  || _die "Generated compose file does not publish 127.0.0.1:$port:8080 - check config.yml (http_port)."
echo "==> Pulling Bitwarden images (first run takes a while)..."
docker compose -f "$BWDATA/docker/docker-compose.yml" pull
./manage.sh updatedb
echo "==> Starting Bitwarden..."
./manage.sh start

# ── Wait for Bitwarden to answer ─────────────────────────────────────────────
echo -n "==> Waiting for Bitwarden on 127.0.0.1:$port"
BW_UP=false
for _ in $(seq 1 60); do
  CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://127.0.0.1:${port}/alive" 2>/dev/null || echo "000")
  if [ "$CODE" = "200" ]; then BW_UP=true; break; fi
  echo -n "."
  sleep 2
done
echo ""

if [[ "$BW_UP" == "true" ]]; then
  echo "==> Bitwarden is up."
else
  echo "WARNING: Bitwarden did not answer within ~2 minutes."
  echo "         Check: (cd $INSTALL_DIR && ./manage.sh status && ./manage.sh logs)"
  read -rp "Continue with the Nginx setup anyway? [y/N] " ans_continue
  [[ "$ans_continue" =~ ^[Yy]$ ]] || exit 1
fi

# ── Let's Encrypt ───────────────────────────────────────────────────────────-
echo ""
read -rp "Would you like to obtain a Let's Encrypt certificate now? [y/N] " ans_cert
if [[ "$ans_cert" =~ ^[Yy]$ ]]; then
  sudo certbot certonly --nginx -d "$domain"
fi

# ── Nginx reverse proxy ─────────────────────────────────────────────────────-
read -rp "Would you like to set up the Nginx reverse proxy? [y/N] " ans_nginx
if [[ "$ans_nginx" =~ ^[Yy]$ ]]; then
  NGINX_AVAIL="/etc/nginx/sites-available/$domain"

  sudo cp "$NGINX_CONF_SRC" "$NGINX_AVAIL"
  sudo sed -i \
    -e "s|bitwarden\.example\.com|$domain|g" \
    -e "s|127\.0\.0\.1:8086|127.0.0.1:$port|g" \
    "$NGINX_AVAIL"
  echo "==> Nginx config written to $NGINX_AVAIL (domain + port substituted)"

  read -rp "Would you like to enable the site (link to sites-enabled)? [y/N] " ans_link
  if [[ "$ans_link" =~ ^[Yy]$ ]]; then
    sudo ln -sf "$NGINX_AVAIL" "/etc/nginx/sites-enabled/$domain"
    echo "==> Symlink created."
  fi

  echo "==> Testing Nginx configuration..."
  sudo nginx -t
  echo "==> Reloading Nginx..."
  sudo systemctl reload nginx
  echo "==> Nginx reloaded."
fi

# ── Done ────────────────────────────────────────────────────────────────────-
echo ""
echo "==> Bitwarden installation complete."
echo "    URL          : https://$domain"
echo "    Next         : register the first account (needs SMTP for email verification)."
echo "    Config       : $BWDATA/config.yml  (then: ./manage.sh rebuild && ./manage.sh restart)"
echo "    Environment  : $ENV_FILE (mode 600 - back this up)"
echo "    Data         : $BWDATA (mssql, core/attachments, identity certificate)"
echo ""
echo "    Useful commands (run from $INSTALL_DIR):"
echo "    Status  : ./manage.sh status"
echo "    Start   : ./manage.sh start"
echo "    Stop    : ./manage.sh stop"
echo "    Logs    : ./manage.sh logs [api|identity|web|mssql|nginx]"
echo "    Backup  : ./manage.sh backup"
echo "    Update  : ./manage.sh update"
echo ""
